language: python
python:
    - 2.7
install:
    - pip install -r requirements.txt --use-mirrors
before_script:
    - psql -c "CREATE ROLE studentenportal NOSUPERUSER CREATEDB PASSWORD 'studentenportal';" -U postgres
    - psql -d template1 -c "CREATE EXTENSION citext;" -U postgres
script:
    - python manage.py collectstatic --noinput --link
    - python manage.py test front
