sudo: required
# python is required for the direct execution of coveralls
language: python
python:
  - "3.7"

git:
  depth: false

services:
  - docker
env:
    - CONTAINER_COVERAGE_HOME_DIR=/srv/www/studentenportal
      RELEASE=`git describe --tags`
      DOCKER_TAGS="studentenportal/studentenportal:latest studentenportal/studentenportal:${RELEASE}"
      UID=`id -u`
      GID=`id -g`

install:
    - pip install -r requirements/testing.txt  # For coveralls/coverage

script:
    - docker-compose up -d
    - docker-compose run --rm studentenportal ./deploy/dev/test.sh
    - docker-compose stop
    - coveralls
    - ./deploy/production/travis-build.bash

deploy:
    on:
      branch: master
      tags: true
    provider: script
    script: ./deploy/production/travis-deploy.bash
