sudo: required
language: python
python:
    - 2.7
services:
  - docker

install:
    - pip install coveralls==0.4.2
    - make Dockerfile-base
    - make Dockerfile-dev

script:
    - ./test.sh
    - coveralls
