language: python
python:
    - 2.7
install:
    - pip install -r requirements/testing.txt --use-mirrors
before_script:
    - psql -c "CREATE ROLE studentenportal NOSUPERUSER LOGIN CREATEDB PASSWORD 'studentenportal';" -U postgres
    - psql -c "CREATE DATABASE studentenportal OWNER studentenportal;" -U postgres
    - psql -d template1 -c "CREATE EXTENSION citext;" -U postgres
    - python manage.py collectstatic --noinput --link
script:
    - ./test.sh
