#
# studentenportal-dev:8000  ----- studentenportal-dev-media:/srv/www//studentenportal/media
#  ||                       \
#  ||                        ---- ./:/srv/www//studentenportal/
#  ||
# postgres-dev ----- postgres-dev-data:/var/lib/postgresql/data
#
version: '2'
services:
  postgres-dev:
    image: postgres:9.3
    restart: always
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    environment:
      TODO: "asdf"
      POSTGRES_PASSWORD: "k9F1bbHiW4o9By1A6tvL"
      POSTGRES_USER: "studentenportal"

  studentenportal-dev:
    # TODO: Mail logging backend
    links:
      - postgres-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: on-failure:3
    volumes:
      - ./:/srv/www/studentenportal
      - studentenportal-dev-media:/srv/www/studentenportal/media
    ports:
      - 8000:8000
    environment:
      DB_HOST: postgres-dev
      DB_USER: studentenportal
      DB_PASSWORD: k9F1bbHiW4o9By1A6tvL

volumes:
    postgres-dev-data:
    studentenportal-dev-media:
