# Note that this docker-compose file is only for development!
#
# studentenportal:8000  ----- studentenportal-media:/srv/www/studentenportal/media
#  ||                       \
#  ||                        ---- ./:/srv/www/studentenportal/
#  ||
# postgres ----- postgres-data:/var/lib/postgresql/data
#
version: '3.5'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: "k9F1bbHiW4o9By1A6tvL"
      POSTGRES_USER: "studentenportal"
    networks:
        - studentenportal-dev

  studentenportal:
    image: studentenportal/dev:latest
    build:
      context: .
      dockerfile: deploy/dev/Dockerfile
      args:
          - UID=${UID-1000}
          - GID=${GID-1000}
    volumes:
      - ./:/srv/www/studentenportal
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "studentenportal"
      POSTGRES_PASSWORD: "k9F1bbHiW4o9By1A6tvL"
      DJANGO_DEBUG: "True"
    networks:
      - studentenportal-dev
    depends_on:
      - postgres

networks:
  studentenportal-dev:
