#  
# studentenportal ----- studentenportal-media:/var/www/studentenportal/media
#  ||__
#  | __ postgres ----- postgres-data:/var/lib/postgresql/data
#  ||__
#  | __ mailserver #TODO: postfix?
#  ||__
#  |___ webserver:80,:443  #TODO: TLS-frontend nginx or haproxy? let's encrypt auto TLS deployment?
#   
#TODO
